version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    networks:
      - selenium-network
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  python-app:
    build:
      context: .
      dockerfile: python.Dockerfile
    container_name: python-selenium
    depends_on:
      - selenium
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
