services:
  # Selenium service
  - name: selenium-chrome
    type: web
    runtime: image
    env: docker
    image:
      url: selenium/standalone-chrome:latest
    plan: free
    port: 4444
    envVars:
      - key: SE_NODE_MAX_SESSIONS
        value: "5"
      - key: SE_NODE_OVERRIDE_MAX_SESSIONS
        value: "true"
    healthCheckPath: "/wd/hub/status"

  # Python application service
  - name: python-selenium
    type: web
    runtime: docker
    env: docker
    dockerfilePath: python.Dockerfile
    plan: free
    dependsOn:
      - name: selenium-chrome
        condition: service_healthy
    envVars:
      - key: SELENIUM_HOST
        value: selenium-chrome  # Reference the Selenium service hostname
