services:
  # Selenium service
  - name: selenium-chrome
    type: web
    runtime: image
    env: docker
    image:
      url: selenium/standalone-chrome:latest
    plan: free
    envVars:
      - key: SE_NODE_MAX_SESSIONS
        value: "5"
      - key: SE_NODE_OVERRIDE_MAX_SESSIONS
        value: "true"
    healthCheckPath: "/wd/hub/status"

  # Python application service
  - name: python-selenium
    type: web
    runtime: docker
    env: docker
    dockerfilePath: python.Dockerfile
    plan: free
    envVars:
      - key: SELENIUM_HOST
        fromService:
          name: selenium-chrome
          type: web
          property: hostport  # Dynamically reference Selenium service's host and port
