# -*- mode: python ; coding: utf-8 -*-
from kivy_deps import sdl2, glew

a = Analysis(
    ['src\\main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'kivy.core.clipboard',
        'kivy.core.window',
        'kivy.core.text',
        'kivy.core.image',
        'kivy.uix.recycleview',
        'kivymd',
        'kivymd.app',
        'kivymd.icon_definitions',
        'kivymd.uix.button',
        'kivymd.uix.label',
        'kivymd.uix.textfield',
        'kivymd.uix.card',
        'kivymd.uix.list',
        'kivymd.uix.widget',
        'kivymd.uix.scrollview',
        'kivymd.uix.screenmanager',
        'kivymd.uix.screen',
        'kivymd.uix.boxlayout',
        'kivymd.uix.relativelayout',
        'kivymd.uix.floatlayout',
        'asynckivy',
        'kivy',
        'materialyoucolor',
        'pillow',
        'asyncio',
        'pandas',
        'selenium',
        'requests'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    Tree('src\\'),
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
    name='webscraper',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
