name: Release Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest  # Or windows-latest if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Upload Executable to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/webscraper.exe  # Path to your executable
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}  # Use the secret token

    - name: Clean up
      run: |
        echo "Finished uploading release."
