name: Release Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Upload Executable to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/webscraper.exe

    - name: Clean up
      run: |
        echo "Finished uploading release."
