name: Release Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest  # You can change this to `windows-latest` if you need a Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checkout the repository to access your code

    - name: Upload Executable to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/webscraper.exe  # Path to your built executable

    - name: Clean up
      run: |
        echo "Finished uploading release."
