name: Release Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Verify Executable Exists
      run: ls -la dist/
    - name: Upload Executable to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/webscraper.exe
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    - name: Clean up
      run: |
        echo "Finished uploading release."
