name: Build and Release PyInstaller Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    # For Linux: Install X server and dependencies
    - name: Install X server (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99.0
        Xvfb :99 -screen 0 1920x1080x24 &

    # Build the executable
    - name: Build with PyInstaller
      run: |
        pyinstaller webscraper.spec
      shell: bash

    # Upload artifact for release
    - name: Upload artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ matrix.os }}
        path: dist/*
